# Generated by Django 3.0.6 on 2020-05-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
