# Generated by Django 3.0.6 on 2020-05-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20200508_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='file',
            name='version',
        ),
    ]
