# Generated by Django 3.0.6 on 2020-05-08 10:13

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20200508_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=file.models.File.user_directory_path),
        ),
    ]
